#pragma once

#include <cstdint>

namespace ClientData
{
	constexpr uintptr_t ANIMATION_DATA_DB = 0x00AD30C8;

	struct AnimationDataRow
	{
		uint32_t id;
		const char* name;
		uint32_t weaponFlags;
		uint32_t bodyFlags;
		uint32_t flags;
		uint32_t fallback;
		uint32_t behaviorId;
		uint32_t behaviorTier;
	};

	constexpr int ANIMATION_CURRENT_OR_NONE = 506;

	enum AnimationId : int32_t
	{
		ANIMATION_WALK = 4,
		ANIMATION_RUN = 5,
		ANIMATION_RUN_BACKWARDS = 13,

		ANIMATION_ATTACK_UNARMED = 16,
		ANIMATION_ATTACK_1H = 17,
		ANIMATION_ATTACK_2H = 18,
		ANIMATION_ATTACK_2H_LOOSE = 19,

		ANIMATION_READY_UNARMED = 25,
		ANIMATION_READY_1H = 26,
		ANIMATION_READY_2H = 27,
		ANIMATION_READY_2H_LOOSE = 28,

		ANIMATION_JUMP_START = 37,
		ANIMATION_FALL = 40,
		ANIMATION_SWIM_IDLE = 41,
		ANIMATION_SWIM = 42,
		ANIMATION_SWIM_BACKWARDS = 45,

		ANIMATION_SPECIAL_1H = 57,
		ANIMATION_SPECIAL_2H = 58,

		ANIMATION_ATTACK_1H_PIERCE = 85,
		ANIMATION_ATTACK_2H_LOOSE_PIERCE = 86,
		ANIMATION_ATTACK_OFFHAND = 87,
		ANIMATION_ATTACK_OFFHAND_PIERCE = 88,

		ANIMATION_READY_RANGED_HOLD = 110,

		ANIMATION_ATTACK_UNARMED_OFFHAND = 117,
		ANIMATION_SPECIAL_UNARMED = 118,

		ANIMATION_CHANNEL_CAST_DIRECTED = 124,
		ANIMATION_CHANNEL_CAST_OMNI = 125,

		ANIMATION_SPRINT = 143,

		ANIMATION_MONK_ATTACK_MAINHAND = 672,
		ANIMATION_MONK_ATTACK_OFFHAND = 674,
		ANIMATION_MONK_READY = 678,
	};
}
