#pragma once

#include <cstdint>

namespace ClientData
{
	constexpr uintptr_t ANIMATION_DATA_DB = 0x00AD30C8 + 0x18;

	struct AnimationDataRow
	{
		uint32_t id;
		const char* name;
		uint32_t weaponFlags;
		uint32_t bodyFlags;
		uint32_t flags;
		uint32_t fallback;
		uint32_t behaviorId;
		uint32_t behaviorTier;
	};

	constexpr int ANIMATION_CURRENT_OR_NONE = 506;

	enum AnimationId : int32_t
	{
		ANIMATION_STAND = 0,
		ANIMATION_STOP = 3,
		ANIMATION_WALK = 4,
		ANIMATION_RUN = 5,
		ANIMATION_RISE = 7,
		ANIMATION_SHUFFLE_LEFT = 11,
		ANIMATION_SHUFFLE_RIGHT = 12,
		ANIMATION_RUN_BACKWARDS = 13,

		ANIMATION_ATTACK_UNARMED = 16,
		ANIMATION_ATTACK_1H = 17,
		ANIMATION_ATTACK_2H = 18,
		ANIMATION_ATTACK_2H_LOOSE = 19,

		// Looping "weapon drawn" ready/combat-idle stances.
		ANIMATION_READY_UNARMED = 25,
		ANIMATION_READY_1H = 26,
		ANIMATION_READY_2H = 27,
		ANIMATION_READY_2H_LOOSE = 28,

		ANIMATION_JUMP_START = 37,
		ANIMATION_JUMP_END = 39,
		ANIMATION_FALL = 40,
		ANIMATION_SWIM_IDLE = 41,
		ANIMATION_SWIM = 42,
		ANIMATION_SWIM_LEFT = 43,
		ANIMATION_SWIM_RIGHT = 44,
		ANIMATION_SWIM_BACKWARDS = 45,

		ANIMATION_SPECIAL_1H = 57,
		ANIMATION_SPECIAL_2H = 58,

		ANIMATION_ATTACK_1H_PIERCE = 85,
		ANIMATION_ATTACK_2H_LOOSE_PIERCE = 86,
		ANIMATION_ATTACK_OFFHAND = 87,
		ANIMATION_ATTACK_OFFHAND_PIERCE = 88,

		ANIMATION_RUN_RIGHT = 92,
		ANIMATION_RUN_LEFT = 93,

		ANIMATION_READY_RANGED_HOLD = 110,

		ANIMATION_ATTACK_UNARMED_OFFHAND = 117,
		ANIMATION_SPECIAL_UNARMED = 118,

		ANIMATION_CHANNEL_CAST_DIRECTED = 124,
		ANIMATION_CHANNEL_CAST_OMNI = 125,

		ANIMATION_FLY = 135,

		ANIMATION_SPRINT = 143,

		ANIMATION_JUMP_LAND_RUN = 187,
		ANIMATION_HOVER = 193,

		ANIMATION_SWIM_RUN = 524,
		ANIMATION_SWIM_WALK = 526,
		ANIMATION_SWIM_WALK_BACKWARDS = 528,
		ANIMATION_SWIM_SPRINT = 530,

		ANIMATION_MOUNT_SWIM_IDLE = 532,
		ANIMATION_MOUNT_SWIM_BACKWARDS = 534,
		ANIMATION_MOUNT_SWIM_LEFT = 536,
		ANIMATION_MOUNT_SWIM_RIGHT = 538,
		ANIMATION_MOUNT_SWIM_RUN = 540,
		ANIMATION_MOUNT_SWIM_SPRINT = 542,
		ANIMATION_MOUNT_SWIM_WALK = 544,
		ANIMATION_MOUNT_SWIM_WALK_BACKWARDS = 546,
		ANIMATION_MOUNT_FLIGHT_IDLE = 548,
		ANIMATION_MOUNT_FLIGHT_BACKWARDS = 550,
		ANIMATION_MOUNT_FLIGHT_LEFT = 552,
		ANIMATION_MOUNT_FLIGHT_RIGHT = 554,
		ANIMATION_MOUNT_FLIGHT_RUN = 556,
		ANIMATION_MOUNT_FLIGHT_SPRINT = 558,
		ANIMATION_MOUNT_FLIGHT_WALK = 560,
		ANIMATION_MOUNT_FLIGHT_WALK_BACKWARDS = 562,
		ANIMATION_MOUNT_FLIGHT_START = 564,
		ANIMATION_MOUNT_SWIM_START = 566,
		ANIMATION_MOUNT_SWIM_LAND = 568,
		ANIMATION_MOUNT_SWIM_LAND_RUN = 570,
		ANIMATION_MOUNT_FLIGHT_LAND = 572,
		ANIMATION_MOUNT_FLIGHT_LAND_RUN = 574,

		ANIMATION_MONK_ATTACK_MAINHAND = 672, // main-hand unarmed swing
		ANIMATION_MONK_ATTACK_OFFHAND = 674,  // off-hand unarmed swing
		ANIMATION_MONK_READY = 678,           // attack idle / combat-ready stance
	};

	constexpr int32_t ANIMATION_MOUNT_VARIANT_FIRST = ANIMATION_MOUNT_SWIM_IDLE;
	constexpr int32_t ANIMATION_MOUNT_VARIANT_LAST = ANIMATION_MOUNT_FLIGHT_LAND_RUN + 1;
}
