#pragma once
#include <Defines.h>

enum CustomOpcodes
{
	SMSG_UPDATE_CUSTOM_COMBAT_RATING = 1311,
	CMSG_TELEPORT_GRAVEYARD_REQUEST = 1312,
	SMSG_RECEIVE_SECURITY_LEVEL = 1313,
	CMSG_CUSTOM_TEST = 1315,
	SMSG_CUSTOM_TEST = 1316,
	CMSG_ITEM_LEVEL_REQUEST = 1317,
	SMSG_ITEM_LEVEL_REQUEST = 1318,
	SMSG_SEND_TEMP_CVAR = 1319,
	SMSG_TB_BULLSHIT = 1320,
	CMSG_CUSTOM_LFG_QUEUE = 1321,
	SMSG_CUSTOM_STAT_TRACK = 1322,
	CMSG_SANITY_CHECK = 1323,
	SMSG_SANITY_CHECK = 1324,
	SMSG_FUCKED_CLIENT_DETECTED = 1325,
	SMSG_CUSTOM_SPELL_MOD_FLAT = 1326,
	SMSG_CUSTOM_SPELL_MOD_PCT = 1327,
	SMSG_REMOVE_CUSTOM_SPELL_MODIFIER = 1328,
	CMSG_REQUEST_CHAR_ENUM_LEVELS = 1329,
	SMSG_REQUEST_CHAR_ENUM_LEVELS = 1330,
	CMSG_GOB_EDITOR_UPDATE = 1331,
	CMSG_GOB_EDITOR_SELECT_NEAREST = 1332,
	SMSG_GOB_EDITOR_SELECT = 1333,

	CMSG_CUSTOM_TALENT_CACHE_REQUEST = 1334,
	CMSG_CUSTOM_TALENT_SMALL_CACHE_REQ = 1335,
	CMSG_CUSTOM_TALENT_POINTS_REQUEST = 1336,
	CMSG_CUSTOM_TALENT_LEARN = 1337,
	CMSG_CUSTOM_TALENT_UNLEARN = 1338,
	CMSG_CUSTOM_TALENT_RESET = 1339,
	CMSG_CUSTOM_TALENT_INSPECT = 1340,
	CMSG_CUSTOM_TALENT_LOADOUT_SWITCH = 1341,
	SMSG_CUSTOM_TALENT_CACHE = 1342,
	SMSG_CUSTOM_TALENT_SMALL_CACHE = 1343,
	SMSG_CUSTOM_TALENT_POINTS = 1344,
	SMSG_CUSTOM_TALENT_LEVEL = 1345,
	SMSG_CUSTOM_TALENT_LEARN_RESPONSE = 1346,
	SMSG_CUSTOM_TALENT_UNLEARN_RESPONSE = 1347,
	SMSG_CUSTOM_TALENT_RESET = 1348,
	SMSG_CUSTOM_TALENT_INSPECT_RESPONSE = 1349,
	SMSG_CUSTOM_TALENT_NEW = 1350,
	SMSG_CUSTOM_TALENT_LEARNT_UPDATE = 1351,

	CMSG_TALENT_EDITOR_SET_LINK = 1352,
	CMSG_TALENT_EDITOR_DELETE_LINKS = 1353,
	CMSG_TALENT_EDITOR_UPDATE_NODE = 1354,
	CMSG_TALENT_EDITOR_DELETE_NODE = 1355,
	CMSG_TALENT_EDITOR_NEW_NODE = 1356,

	SMSG_CUSTOM_TEST_FRAME = 1357,
	CMSG_CUSTOM_TEST_FRAME_REPLY = 1358,

	CMSG_UNIT_LEVEL_CACHE_REQUEST = 1359,
	SMSG_UNIT_LEVEL_CACHE_RESPONSE = 1360,

	CMSG_GEM_SOCKET_LIST_REQUEST = 1361,
	SMSG_GEM_SOCKET_LIST = 1362,
	CMSG_GEM_SOCKET_INSERT = 1363,
	CMSG_GEM_SOCKET_REMOVE = 1364,
	SMSG_GEM_SOCKET_ERROR = 1366,

	SMSG_CUSTOM_TALENT_ITEM_GRANTED_UPDATE = 1365,

	CMSG_ITEM_LEVEL_BREAKDOWN_REQUEST = 1367,
	SMSG_ITEM_LEVEL_BREAKDOWN = 1368,

	SMSG_FEATURE_TOGGLE = 1369,
	CMSG_FEATURE_TOGGLE_REQUEST = 1370,

	CMSG_CUSTOM_TALENT_IMPORT = 1371,

	SMSG_ITEM_DB_CACHE = 1372,

	// Generic client-DBC record patching. One opcode handles add/replace/remove
	// for every native WowClientDB storage (Spell, Item, Map, ...). See
	// Packets/DBCRecordPackets.cpp.
	SMSG_DBC_RECORD_UPDATE = 1373,

	SMSG_STREAMING_START = 1374,

	SMSG_BACKGROUND_DOWNLOAD = 1375,

	SMSG_PRIME_LOOT_TARGET = 1376,

	NUM_CUSTOM_MSG_TYPES
};

enum PlayerFlags
{
	PLAYER_FLAGS_GHOST = 0x10,
};

enum CVarFlags : uint32_t
{
	CVarFlags_ReadOnly = 0x4,
	CVarFlags_CheckTaint = 0x8,
	CVarFlags_HideFromUser = 0x40,
	CVarFlags_ReadOnlyForUser = 0x100,
};

enum ItemSpelltriggerType : uint8
{
	ITEM_SPELLTRIGGER_ON_USE = 0,
	ITEM_SPELLTRIGGER_ON_EQUIP = 1,
	ITEM_SPELLTRIGGER_CHANCE_ON_HIT = 2,
	ITEM_SPELLTRIGGER_SOULSTONE = 4,
	ITEM_SPELLTRIGGER_ON_NO_DELAY_USE = 5,
	ITEM_SPELLTRIGGER_LEARN_SPELL_ID = 6
};
