#pragma once

#include <cstdint>

namespace ClientData
{
	enum FrameXMLEvent : uint32_t
	{
		EVENT_ACTIONBAR_SLOT_CHANGED = 176,
		EVENT_LFG_ROLE_UPDATE = 506,
		EVENT_PLAYER_TALENT_UPDATE = 625,
	};

	enum GameError : uint32_t
	{
		GERR_LEARN_SPELL_S = 59,
		GERR_LEARN_ABILITY_S = 60,
		GERR_SPELL_UNLEARNED_S = 352,
	};

	// HitInfo bits carried by SMSG_ATTACKERSTATEUPDATE and the round struct the
	// client builds from it.
	enum HitInfo : uint32_t
	{
		HITINFO_AFFECTS_VICTIM = 0x00000002,
		HITINFO_OFFHAND = 0x00000004,
		HITINFO_MISS = 0x00000010,
		HITINFO_CRITICAL_HIT = 0x00000200,
		HITINFO_NO_ANIMATION = 0x00040000,
	};

	enum ItemClass : uint8_t
	{
		ITEM_CLASS_CONSUMABLE = 0,
		ITEM_CLASS_CONTAINER = 1,
		ITEM_CLASS_WEAPON = 2,
		ITEM_CLASS_GEM = 3,
		ITEM_CLASS_ARMOR = 4,
		ITEM_CLASS_REAGENT = 5,
		ITEM_CLASS_PROJECTILE = 6,
		ITEM_CLASS_TRADE_GOODS = 7,
		ITEM_CLASS_GENERIC = 8,
		ITEM_CLASS_RECIPE = 9,
		ITEM_CLASS_MONEY = 10,
		ITEM_CLASS_QUIVER = 11,
		ITEM_CLASS_QUEST = 12,
		ITEM_CLASS_KEY = 13,
		ITEM_CLASS_PERMANENT = 14,
		ITEM_CLASS_MISC = 15,
		ITEM_CLASS_GLYPH = 16,
	};

	enum ItemSubclassWeapon : uint8_t
	{
		ITEM_SUBCLASS_WEAPON_AXE = 0,
		ITEM_SUBCLASS_WEAPON_AXE2 = 1,
		ITEM_SUBCLASS_WEAPON_BOW = 2,
		ITEM_SUBCLASS_WEAPON_GUN = 3,
		ITEM_SUBCLASS_WEAPON_MACE = 4,
		ITEM_SUBCLASS_WEAPON_MACE2 = 5,
		ITEM_SUBCLASS_WEAPON_POLEARM = 6,
		ITEM_SUBCLASS_WEAPON_SWORD = 7,
		ITEM_SUBCLASS_WEAPON_SWORD2 = 8,
		ITEM_SUBCLASS_WEAPON_OBSOLETE = 9,
		ITEM_SUBCLASS_WEAPON_STAFF = 10,
		ITEM_SUBCLASS_WEAPON_EXOTIC = 11,
		ITEM_SUBCLASS_WEAPON_EXOTIC2 = 12,
		ITEM_SUBCLASS_WEAPON_FIST = 13,
		ITEM_SUBCLASS_WEAPON_MISC = 14,
		ITEM_SUBCLASS_WEAPON_DAGGER = 15,
		ITEM_SUBCLASS_WEAPON_THROWN = 16,
		ITEM_SUBCLASS_WEAPON_SPEAR = 17,
		ITEM_SUBCLASS_WEAPON_CROSSBOW = 18,
		ITEM_SUBCLASS_WEAPON_WAND = 19,
		ITEM_SUBCLASS_WEAPON_FISHING_POLE = 20,
	};

	inline bool IsRangedWeaponSubclass(uint8_t subclass)
	{
		return subclass == ITEM_SUBCLASS_WEAPON_BOW || subclass == ITEM_SUBCLASS_WEAPON_GUN || subclass == ITEM_SUBCLASS_WEAPON_CROSSBOW;
	}

	enum Powers : int32_t
	{
		POWER_MANA = 0,
		POWER_RAGE = 1,
		POWER_FOCUS = 2,
		POWER_ENERGY = 3,
		POWER_HAPPINESS = 4,
		POWER_RUNES = 5,
		POWER_RUNIC_POWER = 7,
	};

	enum SpellCastResult : uint32_t
	{
		SPELL_FAILED_MOVING = 51,
	};

	enum SpellFamilyNames : uint32_t
	{
		SPELLFAMILY_GENERIC = 0,
		SPELLFAMILY_UNK1 = 1,
		SPELLFAMILY_CRAFTING = 2,
		SPELLFAMILY_MAGE = 3,
		SPELLFAMILY_WARRIOR = 4,
		SPELLFAMILY_WARLOCK = 5,
		SPELLFAMILY_PRIEST = 6,
		SPELLFAMILY_DRUID = 7,
		SPELLFAMILY_ROGUE = 8,
		SPELLFAMILY_HUNTER = 9,
		SPELLFAMILY_PALADIN = 10,
		SPELLFAMILY_SHAMAN = 11,
		SPELLFAMILY_UNK2 = 12,
		SPELLFAMILY_POTION = 13,
		SPELLFAMILY_DEATHKNIGHT = 15,
		SPELLFAMILY_PET = 17,
	};

	enum SpellEffect : uint32_t
	{
		SPELL_EFFECT_TRADE_SKILL = 47,
		SPELL_EFFECT_ATTACK = 78,
		SPELL_EFFECT_TITAN_GRIP = 155,
	};

	enum SpellSchools : uint32_t
	{
		SPELL_SCHOOL_NORMAL = 0, // TITLE Physical
		SPELL_SCHOOL_HOLY = 1,   // TITLE Holy
		SPELL_SCHOOL_FIRE = 2,   // TITLE Fire
		SPELL_SCHOOL_NATURE = 3, // TITLE Nature
		SPELL_SCHOOL_FROST = 4,  // TITLE Frost
		SPELL_SCHOOL_SHADOW = 5, // TITLE Shadow
		SPELL_SCHOOL_ARCANE = 6, // TITLE Arcane
		MAX_SPELL_SCHOOL = 7,    // SKIP
	};

	enum UnitFlags2 : uint32_t
	{
		UNIT_FLAG2_REGENERATE_POWER = 0x00000800,
	};
}
