#pragma once

#include <cstdint>
#include <ClientData/MathTypes.h>
#include <ClientData/Units.h>
#include <ClientData/Players.h>

namespace ClientData
{
	enum ObjectTypeMask : uint32_t
	{
		TYPEMASK_OBJECT = 0x0001,
		TYPEMASK_ITEM = 0x0002,
		TYPEMASK_CONTAINER = 0x0004,
		TYPEMASK_UNIT = 0x0008,
		TYPEMASK_PLAYER = 0x0010,
		TYPEMASK_GAMEOBJECT = 0x0020,
		TYPEMASK_DYNAMICOBJECT = 0x0040,
		TYPEMASK_CORPSE = 0x0080,
	};

	enum TypeID
	{
		TYPEID_OBJECT = 0,
		TYPEID_ITEM = 1,
		TYPEID_CONTAINER = 2,
		TYPEID_UNIT = 3,
		TYPEID_PLAYER = 4,
		TYPEID_GAMEOBJECT = 5,
		TYPEID_DYNAMICOBJECT = 6,
		TYPEID_CORPSE = 7,
		NUM_TYPEIDS = 8,
	};

	enum EObjectFields
	{
		OBJECT_FIELD_GUID = 0x0000,    // Size: 2, Type: LONG,  Flags: PUBLIC
		OBJECT_FIELD_TYPE = 0x0002,    // Size: 1, Type: INT,   Flags: PUBLIC
		OBJECT_FIELD_ENTRY = 0x0003,   // Size: 1, Type: INT,   Flags: PUBLIC
		OBJECT_FIELD_SCALE_X = 0x0004, // Size: 1, Type: FLOAT, Flags: PUBLIC
		OBJECT_FIELD_PADDING = 0x0005, // Size: 1, Type: INT,   Flags: NONE
		OBJECT_END = 0x0006,
	};

	enum EGameObjectFields
	{
		OBJECT_FIELD_CREATED_BY = OBJECT_END + 0x0000,   // Size: 2, Type: LONG,      Flags: PUBLIC
		GAMEOBJECT_DISPLAYID = OBJECT_END + 0x0002,      // Size: 1, Type: INT,       Flags: PUBLIC
		GAMEOBJECT_FLAGS = OBJECT_END + 0x0003,          // Size: 1, Type: INT,       Flags: PUBLIC
		GAMEOBJECT_PARENTROTATION = OBJECT_END + 0x0004, // Size: 4, Type: FLOAT,     Flags: PUBLIC
		GAMEOBJECT_DYNAMIC = OBJECT_END + 0x0008,        // Size: 1, Type: TWO_SHORT, Flags: DYNAMIC
		GAMEOBJECT_FACTION = OBJECT_END + 0x0009,        // Size: 1, Type: INT,       Flags: PUBLIC
		GAMEOBJECT_LEVEL = OBJECT_END + 0x000A,          // Size: 1, Type: INT,       Flags: PUBLIC
		GAMEOBJECT_BYTES_1 = OBJECT_END + 0x000B,        // Size: 1, Type: BYTES,     Flags: PUBLIC
		GAMEOBJECT_END = OBJECT_END + 0x000C,
	};

	enum GameobjectTypes
	{
		GAMEOBJECT_TYPE_DOOR = 0,
		GAMEOBJECT_TYPE_BUTTON = 1,
		GAMEOBJECT_TYPE_QUESTGIVER = 2,
		GAMEOBJECT_TYPE_CHEST = 3,
		GAMEOBJECT_TYPE_BINDER = 4,
		GAMEOBJECT_TYPE_GENERIC = 5,
		GAMEOBJECT_TYPE_TRAP = 6,
		GAMEOBJECT_TYPE_CHAIR = 7,
		GAMEOBJECT_TYPE_SPELL_FOCUS = 8,
		GAMEOBJECT_TYPE_TEXT = 9,
		GAMEOBJECT_TYPE_GOOBER = 10,
		GAMEOBJECT_TYPE_TRANSPORT = 11,
		GAMEOBJECT_TYPE_AREADAMAGE = 12,
		GAMEOBJECT_TYPE_CAMERA = 13,
		GAMEOBJECT_TYPE_MAP_OBJECT = 14,
		GAMEOBJECT_TYPE_MO_TRANSPORT = 15,
		GAMEOBJECT_TYPE_DUEL_ARBITER = 16,
		GAMEOBJECT_TYPE_FISHINGNODE = 17,
		GAMEOBJECT_TYPE_SUMMONING_RITUAL = 18,
		GAMEOBJECT_TYPE_MAILBOX = 19,
		GAMEOBJECT_TYPE_DO_NOT_USE = 20,
		GAMEOBJECT_TYPE_GUARDPOST = 21,
		GAMEOBJECT_TYPE_SPELLCASTER = 22,
		GAMEOBJECT_TYPE_MEETINGSTONE = 23,
		GAMEOBJECT_TYPE_FLAGSTAND = 24,
		GAMEOBJECT_TYPE_FISHINGHOLE = 25,
		GAMEOBJECT_TYPE_FLAGDROP = 26,
		GAMEOBJECT_TYPE_MINI_GAME = 27,
		GAMEOBJECT_TYPE_DO_NOT_USE_2 = 28,
		GAMEOBJECT_TYPE_CAPTURE_POINT = 29,
		GAMEOBJECT_TYPE_AURA_GENERATOR = 30,
		GAMEOBJECT_TYPE_DUNGEON_DIFFICULTY = 31,
		GAMEOBJECT_TYPE_BARBER_CHAIR = 32,
		GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING = 33,
		GAMEOBJECT_TYPE_GUILD_BANK = 34,
		GAMEOBJECT_TYPE_TRAPDOOR = 35,
	};

	enum EUnitFields
	{
		UNIT_FIELD_CHARM = OBJECT_END + 0x0000,                                 // Size: 2, Type: LONG,      Flags: PUBLIC
		UNIT_FIELD_SUMMON = OBJECT_END + 0x0002,                                // Size: 2, Type: LONG,      Flags: PUBLIC
		UNIT_FIELD_CRITTER = OBJECT_END + 0x0004,                               // Size: 2, Type: LONG,      Flags: PRIVATE
		UNIT_FIELD_CHARMEDBY = OBJECT_END + 0x0006,                             // Size: 2, Type: LONG,      Flags: PUBLIC
		UNIT_FIELD_SUMMONEDBY = OBJECT_END + 0x0008,                            // Size: 2, Type: LONG,      Flags: PUBLIC
		UNIT_FIELD_CREATEDBY = OBJECT_END + 0x000A,                             // Size: 2, Type: LONG,      Flags: PUBLIC
		UNIT_FIELD_TARGET = OBJECT_END + 0x000C,                                // Size: 2, Type: LONG,      Flags: PUBLIC
		UNIT_FIELD_CHANNEL_OBJECT = OBJECT_END + 0x000E,                        // Size: 2, Type: LONG,      Flags: PUBLIC
		UNIT_CHANNEL_SPELL = OBJECT_END + 0x0010,                               // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_BYTES_0 = OBJECT_END + 0x0011,                               // Size: 1, Type: BYTES,     Flags: PUBLIC
		UNIT_FIELD_HEALTH = OBJECT_END + 0x0012,                                // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_POWER1 = OBJECT_END + 0x0013,                                // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_POWER2 = OBJECT_END + 0x0014,                                // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_POWER3 = OBJECT_END + 0x0015,                                // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_POWER4 = OBJECT_END + 0x0016,                                // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_POWER5 = OBJECT_END + 0x0017,                                // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_POWER6 = OBJECT_END + 0x0018,                                // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_POWER7 = OBJECT_END + 0x0019,                                // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_MAXHEALTH = OBJECT_END + 0x001A,                             // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_MAXPOWER1 = OBJECT_END + 0x001B,                             // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_MAXPOWER2 = OBJECT_END + 0x001C,                             // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_MAXPOWER3 = OBJECT_END + 0x001D,                             // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_MAXPOWER4 = OBJECT_END + 0x001E,                             // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_MAXPOWER5 = OBJECT_END + 0x001F,                             // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_MAXPOWER6 = OBJECT_END + 0x0020,                             // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_MAXPOWER7 = OBJECT_END + 0x0021,                             // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER = OBJECT_END + 0x0022,             // Size: 7, Type: FLOAT,     Flags: PRIVATE, OWNER
		UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER = OBJECT_END + 0x0029, // Size: 7, Type: FLOAT,     Flags: PRIVATE, OWNER
		UNIT_FIELD_LEVEL = OBJECT_END + 0x0030,                                 // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_FACTIONTEMPLATE = OBJECT_END + 0x0031,                       // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_VIRTUAL_ITEM_SLOT_ID = OBJECT_END + 0x0032,                        // Size: 3, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_FLAGS = OBJECT_END + 0x0035,                                 // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_FLAGS_2 = OBJECT_END + 0x0036,                               // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_AURASTATE = OBJECT_END + 0x0037,                             // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_BASEATTACKTIME = OBJECT_END + 0x0038,                        // Size: 2, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_RANGEDATTACKTIME = OBJECT_END + 0x003A,                      // Size: 1, Type: INT,       Flags: PRIVATE
		UNIT_FIELD_BOUNDINGRADIUS = OBJECT_END + 0x003B,                        // Size: 1, Type: FLOAT,     Flags: PUBLIC
		UNIT_FIELD_COMBATREACH = OBJECT_END + 0x003C,                           // Size: 1, Type: FLOAT,     Flags: PUBLIC
		UNIT_FIELD_DISPLAYID = OBJECT_END + 0x003D,                             // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_NATIVEDISPLAYID = OBJECT_END + 0x003E,                       // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_MOUNTDISPLAYID = OBJECT_END + 0x003F,                        // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_MINDAMAGE = OBJECT_END + 0x0040,                             // Size: 1, Type: FLOAT,     Flags: PRIVATE, OWNER, PARTY_LEADER
		UNIT_FIELD_MAXDAMAGE = OBJECT_END + 0x0041,                             // Size: 1, Type: FLOAT,     Flags: PRIVATE, OWNER, PARTY_LEADER
		UNIT_FIELD_MINOFFHANDDAMAGE = OBJECT_END + 0x0042,                      // Size: 1, Type: FLOAT,     Flags: PRIVATE, OWNER, PARTY_LEADER
		UNIT_FIELD_MAXOFFHANDDAMAGE = OBJECT_END + 0x0043,                      // Size: 1, Type: FLOAT,     Flags: PRIVATE, OWNER, PARTY_LEADER
		UNIT_FIELD_BYTES_1 = OBJECT_END + 0x0044,                               // Size: 1, Type: BYTES,     Flags: PUBLIC
		UNIT_FIELD_PETNUMBER = OBJECT_END + 0x0045,                             // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_PET_NAME_TIMESTAMP = OBJECT_END + 0x0046,                    // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_PETEXPERIENCE = OBJECT_END + 0x0047,                         // Size: 1, Type: INT,       Flags: OWNER
		UNIT_FIELD_PETNEXTLEVELEXP = OBJECT_END + 0x0048,                       // Size: 1, Type: INT,       Flags: OWNER
		UNIT_DYNAMIC_FLAGS = OBJECT_END + 0x0049,                               // Size: 1, Type: INT,       Flags: DYNAMIC
		UNIT_MOD_CAST_SPEED = OBJECT_END + 0x004A,                              // Size: 1, Type: FLOAT,     Flags: PUBLIC
		UNIT_CREATED_BY_SPELL = OBJECT_END + 0x004B,                            // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_NPC_FLAGS = OBJECT_END + 0x004C,                                   // Size: 1, Type: INT,       Flags: DYNAMIC
		UNIT_NPC_EMOTESTATE = OBJECT_END + 0x004D,                              // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_STAT0 = OBJECT_END + 0x004E,                                 // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_STAT1 = OBJECT_END + 0x004F,                                 // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_STAT2 = OBJECT_END + 0x0050,                                 // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_STAT3 = OBJECT_END + 0x0051,                                 // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_STAT4 = OBJECT_END + 0x0052,                                 // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_POSSTAT0 = OBJECT_END + 0x0053,                              // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_POSSTAT1 = OBJECT_END + 0x0054,                              // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_POSSTAT2 = OBJECT_END + 0x0055,                              // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_POSSTAT3 = OBJECT_END + 0x0056,                              // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_POSSTAT4 = OBJECT_END + 0x0057,                              // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_NEGSTAT0 = OBJECT_END + 0x0058,                              // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_NEGSTAT1 = OBJECT_END + 0x0059,                              // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_NEGSTAT2 = OBJECT_END + 0x005A,                              // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_NEGSTAT3 = OBJECT_END + 0x005B,                              // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_NEGSTAT4 = OBJECT_END + 0x005C,                              // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_RESISTANCES = OBJECT_END + 0x005D,                           // Size: 7, Type: INT,       Flags: PRIVATE, OWNER, PARTY_LEADER
		UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE = OBJECT_END + 0x0064,            // Size: 7, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE = OBJECT_END + 0x006B,            // Size: 7, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_BASE_MANA = OBJECT_END + 0x0072,                             // Size: 1, Type: INT,       Flags: PUBLIC
		UNIT_FIELD_BASE_HEALTH = OBJECT_END + 0x0073,                           // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_BYTES_2 = OBJECT_END + 0x0074,                               // Size: 1, Type: BYTES,     Flags: PUBLIC
		UNIT_FIELD_ATTACK_POWER = OBJECT_END + 0x0075,                          // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_ATTACK_POWER_MODS = OBJECT_END + 0x0076,                     // Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER
		UNIT_FIELD_ATTACK_POWER_MULTIPLIER = OBJECT_END + 0x0077,               // Size: 1, Type: FLOAT,     Flags: PRIVATE, OWNER
		UNIT_FIELD_RANGED_ATTACK_POWER = OBJECT_END + 0x0078,                   // Size: 1, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_RANGED_ATTACK_POWER_MODS = OBJECT_END + 0x0079,              // Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER
		UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER = OBJECT_END + 0x007A,        // Size: 1, Type: FLOAT,     Flags: PRIVATE, OWNER
		UNIT_FIELD_MINRANGEDDAMAGE = OBJECT_END + 0x007B,                       // Size: 1, Type: FLOAT,     Flags: PRIVATE, OWNER
		UNIT_FIELD_MAXRANGEDDAMAGE = OBJECT_END + 0x007C,                       // Size: 1, Type: FLOAT,     Flags: PRIVATE, OWNER
		UNIT_FIELD_POWER_COST_MODIFIER = OBJECT_END + 0x007D,                   // Size: 7, Type: INT,       Flags: PRIVATE, OWNER
		UNIT_FIELD_POWER_COST_MULTIPLIER = OBJECT_END + 0x0084,                 // Size: 7, Type: FLOAT,     Flags: PRIVATE, OWNER
		UNIT_FIELD_MAXHEALTHMODIFIER = OBJECT_END + 0x008B,                     // Size: 1, Type: FLOAT,     Flags: PRIVATE, OWNER
		UNIT_FIELD_HOVERHEIGHT = OBJECT_END + 0x008C,                           // Size: 1, Type: FLOAT,     Flags: PUBLIC
		UNIT_FIELD_PADDING = OBJECT_END + 0x008D,                               // Size: 1, Type: INT,       Flags: NONE
		UNIT_END = OBJECT_END + 0x008E,

		PLAYER_DUEL_ARBITER = UNIT_END + 0x0000,    // Size: 2,   Type: LONG,      Flags: PUBLIC
		PLAYER_FLAGS = UNIT_END + 0x0002,           // Size: 1,   Type: INT,       Flags: PUBLIC
		PLAYER_GUILDID = UNIT_END + 0x0003,         // Size: 1,   Type: INT,       Flags: PUBLIC
		PLAYER_GUILDRANK = UNIT_END + 0x0004,       // Size: 1,   Type: INT,       Flags: PUBLIC
		PLAYER_BYTES = UNIT_END + 0x0005,           // Size: 1,   Type: BYTES,     Flags: PUBLIC
		PLAYER_BYTES_2 = UNIT_END + 0x0006,         // Size: 1,   Type: BYTES,     Flags: PUBLIC
		PLAYER_BYTES_3 = UNIT_END + 0x0007,         // Size: 1,   Type: BYTES,     Flags: PUBLIC
		PLAYER_DUEL_TEAM = UNIT_END + 0x0008,       // Size: 1,   Type: INT,       Flags: PUBLIC
		PLAYER_GUILD_TIMESTAMP = UNIT_END + 0x0009, // Size: 1,   Type: INT,       Flags: PUBLIC
		PLAYER_QUEST_LOG_1_1 = UNIT_END + 0x000A,   // Size: 1,   Type: INT,       Flags: PARTY_MEMBER
		PLAYER_QUEST_LOG_1_2 = UNIT_END + 0x000B,   // Size: 1,   Type: INT,       Flags: PRIVATE
		PLAYER_QUEST_LOG_1_3 = UNIT_END + 0x000C,   // Size: 2,   Type: TWO_SHORT, Flags: PRIVATE
		PLAYER_QUEST_LOG_1_4 = UNIT_END + 0x000E,   // Size: 1,   Type: INT,       Flags: PRIVATE
		PLAYER_QUEST_LOG_2_1 = UNIT_END + 0x000F,
		PLAYER_QUEST_LOG_2_2 = UNIT_END + 0x0010,
		PLAYER_QUEST_LOG_2_3 = UNIT_END + 0x0011,
		PLAYER_QUEST_LOG_2_5 = UNIT_END + 0x0013,
		PLAYER_QUEST_LOG_3_1 = UNIT_END + 0x0014,
		PLAYER_QUEST_LOG_3_2 = UNIT_END + 0x0015,
		PLAYER_QUEST_LOG_3_3 = UNIT_END + 0x0016,
		PLAYER_QUEST_LOG_3_5 = UNIT_END + 0x0018,
		PLAYER_QUEST_LOG_4_1 = UNIT_END + 0x0019,
		PLAYER_QUEST_LOG_4_2 = UNIT_END + 0x001A,
		PLAYER_QUEST_LOG_4_3 = UNIT_END + 0x001B,
		PLAYER_QUEST_LOG_4_5 = UNIT_END + 0x001D,
		PLAYER_QUEST_LOG_5_1 = UNIT_END + 0x001E,
		PLAYER_QUEST_LOG_5_2 = UNIT_END + 0x001F,
		PLAYER_QUEST_LOG_5_3 = UNIT_END + 0x0020,
		PLAYER_QUEST_LOG_5_5 = UNIT_END + 0x0022,
		PLAYER_QUEST_LOG_6_1 = UNIT_END + 0x0023,
		PLAYER_QUEST_LOG_6_2 = UNIT_END + 0x0024,
		PLAYER_QUEST_LOG_6_3 = UNIT_END + 0x0025,
		PLAYER_QUEST_LOG_6_5 = UNIT_END + 0x0027,
		PLAYER_QUEST_LOG_7_1 = UNIT_END + 0x0028,
		PLAYER_QUEST_LOG_7_2 = UNIT_END + 0x0029,
		PLAYER_QUEST_LOG_7_3 = UNIT_END + 0x002A,
		PLAYER_QUEST_LOG_7_5 = UNIT_END + 0x002C,
		PLAYER_QUEST_LOG_8_1 = UNIT_END + 0x002D,
		PLAYER_QUEST_LOG_8_2 = UNIT_END + 0x002E,
		PLAYER_QUEST_LOG_8_3 = UNIT_END + 0x002F,
		PLAYER_QUEST_LOG_8_5 = UNIT_END + 0x0031,
		PLAYER_QUEST_LOG_9_1 = UNIT_END + 0x0032,
		PLAYER_QUEST_LOG_9_2 = UNIT_END + 0x0033,
		PLAYER_QUEST_LOG_9_3 = UNIT_END + 0x0034,
		PLAYER_QUEST_LOG_9_5 = UNIT_END + 0x0036,
		PLAYER_QUEST_LOG_10_1 = UNIT_END + 0x0037,
		PLAYER_QUEST_LOG_10_2 = UNIT_END + 0x0038,
		PLAYER_QUEST_LOG_10_3 = UNIT_END + 0x0039,
		PLAYER_QUEST_LOG_10_5 = UNIT_END + 0x003B,
		PLAYER_QUEST_LOG_11_1 = UNIT_END + 0x003C,
		PLAYER_QUEST_LOG_11_2 = UNIT_END + 0x003D,
		PLAYER_QUEST_LOG_11_3 = UNIT_END + 0x003E,
		PLAYER_QUEST_LOG_11_5 = UNIT_END + 0x0040,
		PLAYER_QUEST_LOG_12_1 = UNIT_END + 0x0041,
		PLAYER_QUEST_LOG_12_2 = UNIT_END + 0x0042,
		PLAYER_QUEST_LOG_12_3 = UNIT_END + 0x0043,
		PLAYER_QUEST_LOG_12_5 = UNIT_END + 0x0045,
		PLAYER_QUEST_LOG_13_1 = UNIT_END + 0x0046,
		PLAYER_QUEST_LOG_13_2 = UNIT_END + 0x0047,
		PLAYER_QUEST_LOG_13_3 = UNIT_END + 0x0048,
		PLAYER_QUEST_LOG_13_5 = UNIT_END + 0x004A,
		PLAYER_QUEST_LOG_14_1 = UNIT_END + 0x004B,
		PLAYER_QUEST_LOG_14_2 = UNIT_END + 0x004C,
		PLAYER_QUEST_LOG_14_3 = UNIT_END + 0x004D,
		PLAYER_QUEST_LOG_14_5 = UNIT_END + 0x004F,
		PLAYER_QUEST_LOG_15_1 = UNIT_END + 0x0050,
		PLAYER_QUEST_LOG_15_2 = UNIT_END + 0x0051,
		PLAYER_QUEST_LOG_15_3 = UNIT_END + 0x0052,
		PLAYER_QUEST_LOG_15_5 = UNIT_END + 0x0054,
		PLAYER_QUEST_LOG_16_1 = UNIT_END + 0x0055,
		PLAYER_QUEST_LOG_16_2 = UNIT_END + 0x0056,
		PLAYER_QUEST_LOG_16_3 = UNIT_END + 0x0057,
		PLAYER_QUEST_LOG_16_5 = UNIT_END + 0x0059,
		PLAYER_QUEST_LOG_17_1 = UNIT_END + 0x005A,
		PLAYER_QUEST_LOG_17_2 = UNIT_END + 0x005B,
		PLAYER_QUEST_LOG_17_3 = UNIT_END + 0x005C,
		PLAYER_QUEST_LOG_17_5 = UNIT_END + 0x005E,
		PLAYER_QUEST_LOG_18_1 = UNIT_END + 0x005F,
		PLAYER_QUEST_LOG_18_2 = UNIT_END + 0x0060,
		PLAYER_QUEST_LOG_18_3 = UNIT_END + 0x0061,
		PLAYER_QUEST_LOG_18_5 = UNIT_END + 0x0063,
		PLAYER_QUEST_LOG_19_1 = UNIT_END + 0x0064,
		PLAYER_QUEST_LOG_19_2 = UNIT_END + 0x0065,
		PLAYER_QUEST_LOG_19_3 = UNIT_END + 0x0066,
		PLAYER_QUEST_LOG_19_5 = UNIT_END + 0x0068,
		PLAYER_QUEST_LOG_20_1 = UNIT_END + 0x0069,
		PLAYER_QUEST_LOG_20_2 = UNIT_END + 0x006A,
		PLAYER_QUEST_LOG_20_3 = UNIT_END + 0x006B,
		PLAYER_QUEST_LOG_20_5 = UNIT_END + 0x006D,
		PLAYER_QUEST_LOG_21_1 = UNIT_END + 0x006E,
		PLAYER_QUEST_LOG_21_2 = UNIT_END + 0x006F,
		PLAYER_QUEST_LOG_21_3 = UNIT_END + 0x0070,
		PLAYER_QUEST_LOG_21_5 = UNIT_END + 0x0072,
		PLAYER_QUEST_LOG_22_1 = UNIT_END + 0x0073,
		PLAYER_QUEST_LOG_22_2 = UNIT_END + 0x0074,
		PLAYER_QUEST_LOG_22_3 = UNIT_END + 0x0075,
		PLAYER_QUEST_LOG_22_5 = UNIT_END + 0x0077,
		PLAYER_QUEST_LOG_23_1 = UNIT_END + 0x0078,
		PLAYER_QUEST_LOG_23_2 = UNIT_END + 0x0079,
		PLAYER_QUEST_LOG_23_3 = UNIT_END + 0x007A,
		PLAYER_QUEST_LOG_23_5 = UNIT_END + 0x007C,
		PLAYER_QUEST_LOG_24_1 = UNIT_END + 0x007D,
		PLAYER_QUEST_LOG_24_2 = UNIT_END + 0x007E,
		PLAYER_QUEST_LOG_24_3 = UNIT_END + 0x007F,
		PLAYER_QUEST_LOG_24_5 = UNIT_END + 0x0081,
		PLAYER_QUEST_LOG_25_1 = UNIT_END + 0x0082,
		PLAYER_QUEST_LOG_25_2 = UNIT_END + 0x0083,
		PLAYER_QUEST_LOG_25_3 = UNIT_END + 0x0084,
		PLAYER_QUEST_LOG_25_5 = UNIT_END + 0x0086,
		PLAYER_VISIBLE_ITEM_1_ENTRYID = UNIT_END + 0x0087,
		PLAYER_VISIBLE_ITEM_1_ENCHANTMENT = UNIT_END + 0x0088,
		PLAYER_VISIBLE_ITEM_2_ENTRYID = UNIT_END + 0x0089,
		PLAYER_VISIBLE_ITEM_2_ENCHANTMENT = UNIT_END + 0x008A,
		PLAYER_VISIBLE_ITEM_3_ENTRYID = UNIT_END + 0x008B,
		PLAYER_VISIBLE_ITEM_3_ENCHANTMENT = UNIT_END + 0x008C,
		PLAYER_VISIBLE_ITEM_4_ENTRYID = UNIT_END + 0x008D,
		PLAYER_VISIBLE_ITEM_4_ENCHANTMENT = UNIT_END + 0x008E,
		PLAYER_VISIBLE_ITEM_5_ENTRYID = UNIT_END + 0x008F,
		PLAYER_VISIBLE_ITEM_5_ENCHANTMENT = UNIT_END + 0x0090,
		PLAYER_VISIBLE_ITEM_6_ENTRYID = UNIT_END + 0x0091,
		PLAYER_VISIBLE_ITEM_6_ENCHANTMENT = UNIT_END + 0x0092,
		PLAYER_VISIBLE_ITEM_7_ENTRYID = UNIT_END + 0x0093,
		PLAYER_VISIBLE_ITEM_7_ENCHANTMENT = UNIT_END + 0x0094,
		PLAYER_VISIBLE_ITEM_8_ENTRYID = UNIT_END + 0x0095,
		PLAYER_VISIBLE_ITEM_8_ENCHANTMENT = UNIT_END + 0x0096,
		PLAYER_VISIBLE_ITEM_9_ENTRYID = UNIT_END + 0x0097,
		PLAYER_VISIBLE_ITEM_9_ENCHANTMENT = UNIT_END + 0x0098,
		PLAYER_VISIBLE_ITEM_10_ENTRYID = UNIT_END + 0x0099,
		PLAYER_VISIBLE_ITEM_10_ENCHANTMENT = UNIT_END + 0x009A,
		PLAYER_VISIBLE_ITEM_11_ENTRYID = UNIT_END + 0x009B,
		PLAYER_VISIBLE_ITEM_11_ENCHANTMENT = UNIT_END + 0x009C,
		PLAYER_VISIBLE_ITEM_12_ENTRYID = UNIT_END + 0x009D,
		PLAYER_VISIBLE_ITEM_12_ENCHANTMENT = UNIT_END + 0x009E,
		PLAYER_VISIBLE_ITEM_13_ENTRYID = UNIT_END + 0x009F,
		PLAYER_VISIBLE_ITEM_13_ENCHANTMENT = UNIT_END + 0x00A0,
		PLAYER_VISIBLE_ITEM_14_ENTRYID = UNIT_END + 0x00A1,
		PLAYER_VISIBLE_ITEM_14_ENCHANTMENT = UNIT_END + 0x00A2,
		PLAYER_VISIBLE_ITEM_15_ENTRYID = UNIT_END + 0x00A3,
		PLAYER_VISIBLE_ITEM_15_ENCHANTMENT = UNIT_END + 0x00A4,
		PLAYER_VISIBLE_ITEM_16_ENTRYID = UNIT_END + 0x00A5,
		PLAYER_VISIBLE_ITEM_16_ENCHANTMENT = UNIT_END + 0x00A6,
		PLAYER_VISIBLE_ITEM_17_ENTRYID = UNIT_END + 0x00A7,
		PLAYER_VISIBLE_ITEM_17_ENCHANTMENT = UNIT_END + 0x00A8,
		PLAYER_VISIBLE_ITEM_18_ENTRYID = UNIT_END + 0x00A9,
		PLAYER_VISIBLE_ITEM_18_ENCHANTMENT = UNIT_END + 0x00AA,
		PLAYER_VISIBLE_ITEM_19_ENTRYID = UNIT_END + 0x00AB,
		PLAYER_VISIBLE_ITEM_19_ENCHANTMENT = UNIT_END + 0x00AC,
		PLAYER_CHOSEN_TITLE = UNIT_END + 0x00AD,
		PLAYER_FAKE_INEBRIATION = UNIT_END + 0x00AE,
		PLAYER_FIELD_PAD_0 = UNIT_END + 0x00AF,
		PLAYER_FIELD_INV_SLOT_HEAD = UNIT_END + 0x00B0,
		PLAYER_FIELD_PACK_SLOT_1 = UNIT_END + 0x00DE,
		PLAYER_FIELD_BANK_SLOT_1 = UNIT_END + 0x00FE,
		PLAYER_FIELD_BANKBAG_SLOT_1 = UNIT_END + 0x0136,
		PLAYER_FIELD_VENDORBUYBACK_SLOT_1 = UNIT_END + 0x0144,
		PLAYER_FIELD_KEYRING_SLOT_1 = UNIT_END + 0x015C,
		PLAYER_FIELD_CURRENCYTOKEN_SLOT_1 = UNIT_END + 0x019C,
		PLAYER_FARSIGHT = UNIT_END + 0x01DC,
		PLAYER__FIELD_KNOWN_TITLES = UNIT_END + 0x01DE,
		PLAYER__FIELD_KNOWN_TITLES1 = UNIT_END + 0x01E0,
		PLAYER__FIELD_KNOWN_TITLES2 = UNIT_END + 0x01E2,
		PLAYER_FIELD_KNOWN_CURRENCIES = UNIT_END + 0x01E4,
		PLAYER_XP = UNIT_END + 0x01E6,
		PLAYER_NEXT_LEVEL_XP = UNIT_END + 0x01E7,
		PLAYER_SKILL_INFO_1_1 = UNIT_END + 0x01E8,
		PLAYER_CHARACTER_POINTS1 = UNIT_END + 0x0368,
		PLAYER_CHARACTER_POINTS2 = UNIT_END + 0x0369,
		PLAYER_TRACK_CREATURES = UNIT_END + 0x036A,
		PLAYER_TRACK_RESOURCES = UNIT_END + 0x036B,
		PLAYER_BLOCK_PERCENTAGE = UNIT_END + 0x036C,
		PLAYER_DODGE_PERCENTAGE = UNIT_END + 0x036D,
		PLAYER_PARRY_PERCENTAGE = UNIT_END + 0x036E,
		PLAYER_EXPERTISE = UNIT_END + 0x036F,
		PLAYER_OFFHAND_EXPERTISE = UNIT_END + 0x0370,
		PLAYER_CRIT_PERCENTAGE = UNIT_END + 0x0371,
		PLAYER_RANGED_CRIT_PERCENTAGE = UNIT_END + 0x0372,
		PLAYER_OFFHAND_CRIT_PERCENTAGE = UNIT_END + 0x0373,
		PLAYER_SPELL_CRIT_PERCENTAGE1 = UNIT_END + 0x0374,
		PLAYER_SHIELD_BLOCK = UNIT_END + 0x037B,
		PLAYER_SHIELD_BLOCK_CRIT_PERCENTAGE = UNIT_END + 0x037C,
		PLAYER_EXPLORED_ZONES_1 = UNIT_END + 0x037D,
		PLAYER_REST_STATE_EXPERIENCE = UNIT_END + 0x03FD,
		PLAYER_FIELD_COINAGE = UNIT_END + 0x03FE,
		PLAYER_FIELD_MOD_DAMAGE_DONE_POS = UNIT_END + 0x03FF,
		PLAYER_FIELD_MOD_DAMAGE_DONE_NEG = UNIT_END + 0x0406,
		PLAYER_FIELD_MOD_DAMAGE_DONE_PCT = UNIT_END + 0x040D,
		PLAYER_FIELD_MOD_HEALING_DONE_POS = UNIT_END + 0x0414,
		PLAYER_FIELD_MOD_HEALING_PCT = UNIT_END + 0x0415,
		PLAYER_FIELD_MOD_HEALING_DONE_PCT = UNIT_END + 0x0416,
		PLAYER_FIELD_MOD_TARGET_RESISTANCE = UNIT_END + 0x0417,
		PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE = UNIT_END + 0x0418,
		PLAYER_FIELD_BYTES = UNIT_END + 0x0419,
		PLAYER_AMMO_ID = UNIT_END + 0x041A,
		PLAYER_SELF_RES_SPELL = UNIT_END + 0x041B,
		PLAYER_FIELD_PVP_MEDALS = UNIT_END + 0x041C,
		PLAYER_FIELD_BUYBACK_PRICE_1 = UNIT_END + 0x041D,
		PLAYER_FIELD_BUYBACK_TIMESTAMP_1 = UNIT_END + 0x0429,
		PLAYER_FIELD_KILLS = UNIT_END + 0x0435,
		PLAYER_FIELD_TODAY_CONTRIBUTION = UNIT_END + 0x0436,
		PLAYER_FIELD_YESTERDAY_CONTRIBUTION = UNIT_END + 0x0437,
		PLAYER_FIELD_LIFETIME_HONORBALE_KILLS = UNIT_END + 0x0438,
		PLAYER_FIELD_BYTES2 = UNIT_END + 0x0439,
		PLAYER_FIELD_WATCHED_FACTION_INDEX = UNIT_END + 0x043A,
		PLAYER_FIELD_COMBAT_RATING_1 = UNIT_END + 0x043B,
		PLAYER_FIELD_ARENA_TEAM_INFO_1_1 = UNIT_END + 0x0454,
		PLAYER_FIELD_HONOR_CURRENCY = UNIT_END + 0x0469,
		PLAYER_FIELD_ARENA_CURRENCY = UNIT_END + 0x046A,
		PLAYER_FIELD_MAX_LEVEL = UNIT_END + 0x046B,
		PLAYER_FIELD_DAILY_QUESTS_1 = UNIT_END + 0x046C,
		PLAYER_RUNE_REGEN_1 = UNIT_END + 0x0485,
		PLAYER_NO_REAGENT_COST_1 = UNIT_END + 0x0489,
		PLAYER_FIELD_GLYPH_SLOTS_1 = UNIT_END + 0x048C,
		PLAYER_FIELD_GLYPHS_1 = UNIT_END + 0x0492,
		PLAYER_GLYPHS_ENABLED = UNIT_END + 0x0498,
		PLAYER_PET_SPELL_POWER = UNIT_END + 0x0499,
		PLAYER_END = UNIT_END + 0x049A,
	};

	enum EGoFields
	{
		GO_FLAG_NONE = 0x00000000,
		GO_FLAG_IN_USE = 0x00000001,
		GO_FLAG_LOCKED = 0x00000002,
		GO_FLAG_INTERACT_COND = 0x00000004,
		GO_FLAG_TRANSPORT = 0x00000008,
		GO_FLAG_NOT_SELECTABLE = 0x00000010,
		GO_FLAG_NODESPAWN = 0x00000020,
		GO_FLAG_TRIGGERED = 0x00000040,
		GO_FLAG_DAMAGED = 0x00000200,
		GO_FLAG_DESTROYED = 0x00000400,
	};

	enum UnitDynFlags
	{
		UNIT_DYNFLAG_NONE = 0x0000,
		UNIT_DYNFLAG_LOOTABLE = 0x0001,
		UNIT_DYNFLAG_TRACK_UNIT = 0x0002,
		UNIT_DYNFLAG_TAPPED = 0x0004,
		UNIT_DYNFLAG_TAPPED_BY_PLAYER = 0x0008,
		UNIT_DYNFLAG_SPECIALINFO = 0x0010,
		UNIT_DYNFLAG_DEAD = 0x0020,
		UNIT_DYNFLAG_REFER_A_FRIEND = 0x0040,
		UNIT_DYNFLAG_TAPPED_BY_ALL_THREAT_LIST = 0x0080,
	};

	struct ObjectFields
	{
		uint64_t OBJECT_FIELD_GUID;
		uint32_t OBJECT_FIELD_TYPE;
		uint32_t OBJECT_FIELD_ENTRY;
		float OBJECT_FIELD_SCALE_X;
		uint32_t OBJECT_FIELD_PADDING;
	};

	struct CGObject
	{
		void* vtable;
		uint32_t padding;
		ObjectFields* ObjectData;
		uint32_t objectClass[49];
	};

	struct CGUnit
	{
		CGObject objectBase;
		UnitFields* unitData;
		uint32_t paddingD4;
		MovementInfo* movementInfo;
		uint32_t padding34[612];
		uint32_t currentCastId;
		uint32_t padding[4];
		uint32_t currentChannelId;
		uint32_t padding2[353];
		// TODO: add rest, currently not needed
	};

	struct CGPlayer
	{
		CGUnit unitBase;
		PlayerFields* PlayerData;
		uint32_t playerClass[1024];
	};
} // namespace ClientData
